# GET all contacts
GET https://three41-p.onrender.com/contacts
Content-Type: application/json

###

# GET a specific contact by ID 
GET https://three41-p.onrender.com/contacts/67d3b0be74022c5eccc180cd


###
# POST a new contact
POST https://three41-p.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Anna",
    "lastName": "Sanches",
    "email": "test@example.com",
    "favoriteColor": "white",
    "birthday": "2007-01-10"
}

###
# PUT to update a contact (REPLACE 'another_contact_id' with a REAL ID from your database)
PUT https://three41-p.onrender.com/contacts/67d3b0be74022c5eccc180cd
Content-Type: application/json

{
    "favoriteColor": "brown"
}
###

# DELETE a contact (REPLACE 'yet_another_id' with a REAL ID from your database)
DELETE https://three41-p.onrender.com/contacts/67d3b0be74022c5eccc180cd

Content-Type: application/json